[package]
name = "outofbears/react-flow"
description = "React Animation Library for Roblox"
version = "0.3.0"
authors = ["Jack Fox <jack@infernal.io>"]
homepage = "https://github.com/outofbears/react-flow"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/outofbears/react-flow"
realm = "shared"

[dependencies]
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
Promise = "evaera/promise@4.0.0"
